### ISSUE TITLE
Data column on maps table still containing markers

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#101]
When creating new map entries, or updating map entries the map data is still holding markers that are now stored natively in the database.

When storing the data column in a row on the map table, the data shouldn't include markers, if those markers are now in the database.

**Comment by lin-d-hop** [comment]
Hi @rogup,
I see this issue is in Review, however I can't see a linked PR or any testing notes. I can only see that you are moving the issue about, and thus assuming you worked on it. Is that right?
When you create a PR you will have a template to fill in that will make this easier to test.
Could you create a PR with the commits that you made to complete this issue?
