### ISSUE TITLE
Write deployment scripts

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#113]
**Description**

Write a script to run on the server to pull the latest code from the development (staging) or main (production) branches, build/transpile the output, and run any outstanding migration/seeding scripts.

**Acceptance Criteria**

Can use 1 command to deploy to staging, and another command to deploy to production.

**Comment by rogup** [comment]
Having the document outlined in #106 would make this easier

**Comment by rogup** [comment]
@King-Mob I've noticed that there's no development branch on the static repo, so https://github.com/DigitalCommons/land-explorer-front-end/wiki/Deployment-Processes isn't quite right. Do you think it's worth making one, so that we can have a QA process for the static pages, or shall we just use 'main' on staging too?

**Comment by King-Mob** [comment]
@rogup yes let's make a development branch, keep it consistent
