### ISSUE TITLE
Editable Descriptions of Drawn Objects

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#123]
**Description**

Drawn objects now that they're managed in the database, have a description as well as a name. The description needs to be visible and editable, particularly now that objects can come from imported data as well.

**Acceptance Criteria**

Can save an imported object as a drawn object and view its description.
Can create a drawn object (marker, polygon, line) and edit its description.

**Comment by King-Mob** [comment]
@rogup some of the work for this issue might already be in this PR: https://github.com/DigitalCommons/land-explorer-back-end/pull/17

**Comment by rogup** [comment]
> @rogup some of the work for this issue might already be in this PR: [DigitalCommons/land-explorer-back-end#17](https://github.com/DigitalCommons/land-explorer-back-end/pull/17)

Cool thanks.

**Comment by lin-d-hop** [comment]
Designs in #126

**Comment by rogup** [comment]
@King-Mob In the acceptance criteria: "Can save an imported object as a drawn object and view its description."

Just to clarify, by imported we mean drawings that were saved from a data layer to our own map? And do we want these descriptions to be editable too? I'm guessing this is the case, since we can't currently distinguish between objects that we imported or created ourselves.

**Comment by rogup** [comment]
I'm also a bit confused by what was implemented in #126
Any users that have access to a data group can edit the title and description of markers in that data group? I thought we only wanted this to be possible for markers that have been saved to our own map?

**Comment by rogup** [comment]
@lin-d-hop The designs in #126 don't include exactly what the popup should look like for a saved drawing in our own map. Currently there's an 'info' button- should we put this where the 'add' button is in the #126 design?

Also, I assume we want to save edits to the description immediately, like we do in #126? If so, I think this is slightly confusing, because it's not clear what changes would be kept/lost if we left the map without clicking save.
I think it's a bit confusing in #126 too e.g. when saving a marker from a layer to the map, all previous changes are saved, even if we don't click 'save'. Maybe we should remove the 'save' button and save all changes immediately, to be consistent?

**Comment by lin-d-hop** [comment]
I'd def be up for auto-save and think we should 100% move in that direction.
However we can't do all that in one go and as a small team working on a tiny project with few users we can sometimes ship imperfect things with imperfect UX.

I believe this work might have been completed already by @King-Mob in another issue. We had a product crossover when John created this issue and I created another almost identical issue. 
@King-Mob to your knowledge is there anything outstanding on this one?

**Comment by rogup** [comment]
My understanding is that @King-Mob implemented the new popup for data group objects, and I'm doing the same for drawn objects that are saved to a map, in which case there are a few bits of the design that need deciding on.

**Comment by lin-d-hop** [comment]
> I'm also a bit confused by what was implemented in https://github.com/DigitalCommons/land-explorer-front-end/issues/126
Any users that have access to a data group can edit the title and description of markers in that data group... double checking this is what we want. I thought we only wanted this to be possible for markers that have been saved to our own map, but I might be misunderstanding how data layers are used?

Is this question still unclear in your mind @rogup? Correct. Any users that have access to a data group can edit the title and description of markers in that data group.

> @lin-d-hop The designs in https://github.com/DigitalCommons/land-explorer-front-end/issues/126 don't include exactly what the popup should look like for a saved drawing in our own map. Currently there's an 'info' button- should we put this where the 'add' button is in the https://github.com/DigitalCommons/land-explorer-front-end/issues/126 design?

Info button gets removed.

> Also, I assume we want to save edits to the description immediately, like we do in https://github.com/DigitalCommons/land-explorer-front-end/issues/126? If so, I think this is slightly confusing, because it's not clear what changes would be kept/lost if we left the map without clicking save.
> I think it's a bit confusing in https://github.com/DigitalCommons/land-explorer-front-end/issues/126 too e.g. when saving a marker from a layer to the map, all previous changes are saved, even if we don't click 'save'. Maybe we should remove the 'save' button and save all changes immediately, to be consistent?

I'd def be up for auto-save and think we should 100% move in that direction.
However we can't do all that in one go and as a small team working on a tiny project with few users we can sometimes ship imperfect things with imperfect UX.

**Comment by rogup** [comment]
@lin-d-hop Thanks, that answers all my questions! :)
