### ISSUE TITLE
Styling on data group popup looks bad when title is long, double line

### ISSUE THREAD

**Issue by King-Mob** [DigitalCommons/land-explorer-front-end#142]
**Describe the bug**

Icons appearing outside of popup boundarys

**To Reproduce**
1. turn on incredible edible datagroup
2. Click on top left marker, northwest, near hollyhead
3. witness

**Expected behaviour**

Keep it all inside the box. maybe make the popup bigger.

**Screenshots/GIFs**
![lx styling bug.png](https://images.zenhubusercontent.com/628f61875373ab28b43a95db/2379babd-8504-4884-82a1-356da3cfeb43)

**Context (please complete the following information):**
 - Device: web view, desktop
 - OS: windows 10
 - Browser chrome
 - Version 107

**Additional context**
don't think we have a style for this eventuality yet

**Comment by lin-d-hop** [comment]
@MelissaMc20 What do you think about this one? I'm not sure having an endlessly increasing box is the styling we want either.

**Comment by MelissaMc20** [comment]
Can you make a grid within the pop out to house those icons? 

![image](https://user-images.githubusercontent.com/59023121/204397394-07a7acb1-9343-48ed-8771-dcea6f4a0502.png)

On the design I made for the new boxes, I've used a separate box here so that when the scroll appears you know the icons sit to the right of the scroll. 
Would the separate icons within the grid then not be affected when the title drops onto a double line? 
I don't mind the double line header & I don't think the box should continously grow

**Comment by lin-d-hop** [comment]
This is looking good to me.

I wonder if, from an accessibility lens, the text in the boxes is still too small? Happy to merge as is but will add to our UX notes doc.
