### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/land-explorer-front-end#163]
We now have deployment scripts to speed up deployment of a new release to staging/production.

The next step is to add Continuous Delivery, so that the new code can be deployed when pushing to development/main.

- Do we want to use GitHub Actions? If the deploy is part of a pipeline that runs on commits to development/main, it could be extended in the future to run tests.
-  Do we want the code to deployed on every push, or to be manually triggered (e.g. maybe with a git tag in the commit, or a button in the GitHub UI?

**Comment by lin-d-hop** [comment]
I'd be happy to explore Github Actions for this.

Before we can prioritise this it would be good to estimate. Do you have an idea of how long this will take @rogup?

**Comment by wu-lee** [comment]
Just as background. The hook-runner service above is good for things which need to be installed on our servers, because it can run in the servers themselves.

Whereas using Actions for this require a bunch of faffing with authentication keys, plus configuring support for this on our servers, to make it possible for a GitHub action to write files to one of our severs securely.  (Think: configuring locked down ssh access to run a specific command, such as rsync, in a specific location. I've done this before, it's possible but not as simple as you'd like.)

What the hook-runner does is to make it possible to run a script on the target server when a GitHub webhook triggers it.  And if you can do that, you can fairly trivially pull and build the code on the server, so no GitHub action is really needed. (I say trivially, but there are still some pain points, like clean check-outs, running non-interactively, logging and reporting, and ensuring that node/npm is available at the correct version, but I think I've solved *most* of those adequately for the case I have. It's light on reporting and is currently open access, so anyone with the right URL could start a build right now.) 

Tests and building packages, on the other hand - these require no deployment, so GitHub actions would be fine, I expect.
