### ISSUE TITLE
Add simple autosave to all actions

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#172]
## Description
Currently when a user makes changes to their saved maps they need to click to save icon to save these changes. With the save icon moving into the menu system this will be much easier to forget. Plus autosave is just a standard these days.

For all map actions, save the map upon each change.
For now we are implementing the simple version of this feature - the whole map is saved every time.
I also need to create a tech debt issue such that only changes are saved (not the whole map resaved) as this will have performance implications.

## Acceptance Criteria
- Whenever a user changes something on a saved map these changes are automatically saved.
- When a map is not yet saved then no auto saving happens. (@king-mob @rogup do you agree?)
- For editing name and descriptions on markers, don't save the map at every button press. When the user clicks the tick to indicate they are done making edits, save at this point

**Comment by rogup** [comment]
@lin-d-hop For editing name and descriptions, I don't think we actually need to autosave the whole map, since we call a more specific API that edits the object directly. I think these autosave changes can just be added in places where the whole map currently needs to be saved for the changes to take effect.

Autosaving after the initial save makes sense to me. So should we also hide the 'save' button after the initial save? Also, I'm wondering whether you think we need an icon somewhere that indicates we are autosaving, like the cloud on Google Docs/Canva/etc.?

**Comment by lin-d-hop** [comment]
Notes from meeting 9/2
1. moving or zooming the map - Don't save the map on these changes.

2. clicking on a marker/poly/line to make it active - Don't save the map on these changes. Active marker.poly/line will not be saved.

3. Untitled maps aren't saved and this is communicated to the user in the same place that we say changes have been saved.

**Comment by lin-d-hop** [comment]
Outstanding on this issue:

1. We're not going to handle any connectivity problems on this issue. This will become a tech debt in the future. For now, if the user loses connection while editing a map no changes will be saved. If the regain connection then the changes will save. However if they close their browser before the changes save any changes will be lost.

2. We need to communicate to the user when the changes were last saved, and when they are up to date. Mel has made the following designs:
![image](https://user-images.githubusercontent.com/8669848/224732309-6b57de4e-8f0f-48a3-b943-b925b790cf95.png)
![image](https://user-images.githubusercontent.com/8669848/224732348-0d2a29a0-5f10-400d-b925-6558e2b53bf0.png)
