### ISSUE TITLE
Reset password link not working

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#181]
**Describe the bug**
Triggering a reset password sends an email that directs to this link: https://app.testing-lx.com/auth/reset-passwordauth/
This link doesn't render.

**To Reproduce**
1. Logout and hit Forgot Password
2. Enter email 
3. Receive email and follow the link
4. The page doesnt render

**Expected behaviour**
I should be directed to a Login page

**Context (please complete the following information):**
Production PC Chrome

**Comment by rogup** [comment]
@lin-d-hop I've done the short-term fix of fixing the link so that it points to the correct place.

But I think we should overhaul the whole password reset process. It would be better to email link to a password reset page, where the user can set a new password themselves, like what happens for most other websites

Currently,

- the new password is emailed in plain text
- the user's password is immediately changed when requested, and anyone can trigger this to happen without authentication
- an email gets sent to a user if they don't have an account, which is spammy
