### ISSUE TITLE
[LX Collab Mapping] Design and implement Share Map UI

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#308]
**Please track under the clockify project [LX Collab Mapping]**

## Description

Following on from #304 

Redesign the Share map screen. Currently the UX is a little confusing, so it would be good to tidy up redundant elements. But the core purpose of this issue is to enable a user to assign access permissions to a user when they are sharing the map.

Current share map:
![Screenshot from 2024-01-19 14-59-03](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/185d0c51-34a6-42f0-bc5f-7a43332efa83)

inspiration:
![Screenshot from 2024-01-16 15-57-11](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/4ce6f903-98d1-4669-ad17-e8d3f132b486)

## Acceptance Criteria
- Remove redundant elements on the Share maps UI
- Own is only available to the map creator.
- When a user is added the permission level of 'write' or 'read' can be assigned.
- The permission levels set here in the UI correlate to the permission levels defined in #307
- ~Unit tests as standard~
-

**Comment by ms0ur1s** [comment]
Hi @lin-d-hop, just dropped a couple of screenshots below. The second just has the dropdown exposed.

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/96bba3d8-480f-4909-a2ba-4486175e30a7)

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/1cdc75d4-94c9-46c0-850b-7911989e99f2)

**Comment by ms0ur1s** [comment]
![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/ab491bf5-d888-496f-836d-fe2f55509f54)

**Comment by lin-d-hop** [comment]
These are great @ms0ur1s. Is there anything you need to progress this?

**Comment by ms0ur1s** [comment]
> These are great @ms0ur1s. Is there anything you need to progress this?

No @lin-d-hop, #308 work is completed, only #306 work outstanding, which I'm organising with Rohit so it can be resolved.

![image](https://github.com/DigitalCommons/land-explorer-front-end/assets/22494228/9f04acf1-9163-4efd-986c-5d17ca83ec35)

**Comment by rogup** [comment]
I did a bit of testing of this and it turns out that the existing backend code for sharing maps was quite buggy, so I needed to fix and re-write a fair bit of it.

Also, I found the pills a bit confusing because they look like they should show the current share state of the map, but weren't displaying this info, so it wasn't clear whether sharing to a new user would remove access to a previous user. And re-sharing a map with a different access level to the same user didn't seem to work. I've updated things so that it's more similar to the GDocs experience, where all current users with access are shown.

All these changes are within the PR linked to #306 so I'll close this ticket
