### ISSUE TITLE
Property Boundary Service failing

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#312]
**Describe the bug**
The property boundaries are not showing at all.

I wonder if the property boundary service has silently failed?

**To Reproduce**
1. Turn on property boundaries layer
2. zoom in to the most zoomy you can
3. Endless 'loading'

**Expected behaviour**
Expect to display the layer

**Screenshots/GIFs**
![Screenshot from 2024-03-26 08-42-12](https://github.com/DigitalCommons/land-explorer-front-end/assets/8669848/f852eda1-4211-4972-a20a-e3f6ee043a2b)

After 5 mins the above was still loading

**Additional context**
Reported by a user.
Maybe related to #311

**Comment by rogup** [comment]
prod-2 had restarted and the PBS app had not started back up, so I started it.

I've fixed the pm2 systemd startup service on prod-2 which wasn't configured properly (and added how to https://github.com/DigitalCommons/technology-and-infrastructure/issues/99#issuecomment-1912331613) so that it can be automated at some point
