### ISSUE TITLE
Move Boundary Service to Hetzner

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#59]
The boundary service is sitting on a lonely little server all by itself while all the other LX stuff parties on Hetzner.

Let's move this one over as well so they can all be friends... and in the event of a server farm fire, all die together.

**Comment by rogup** [comment]
@wu-lee has suggested we should move everything (this boundary service and also eventually the LX apps) onto the same DCC servers - the dev and prod servers on Scaleways that mykomaps use. This would make them easier to maintain and redeploy.

We should also apparently use Ansible and/or Docker, which also helps with maintainence and deploying things automatically. Especially since @King-Mob and I won't be around as much over the next few months, and @wu-lee doesn't know much about the manual deployment process for LX. Ansible is already set up on the Scaleways servers so it would be easier to do it there.

Then they could all easily be moved to Hetzner if we want.

@lin-d-hop How does this plan sound? Are you happy for me to move this boundary service to the mykomaps server as a first step?

**Comment by lin-d-hop** [comment]
This sounds like a question for an all hands meeting to me. Can we pause on this until the meeting next week?

There are so many bugs that we can focus on in the meantime.

**Comment by rogup** [comment]
In the All Hands, we decided to proceed with moving the Boundary service to the DCC server, as part of a general plan to move all our different products' servers to the same host on Scaleways https://docs.google.com/document/d/1dXKuTzfGpgCUVLU9LF-LrWoJ97O2Z8uOQf3x2MiRu9M/edit

**Comment by rogup** [comment]
@wu-lee Are you okay to set up the Ansible playbook to deploy the boundary MySql server? We currently give it 40GB storage (and it uses about 21GB atm). I'll send you sensitive info on Element e.g. IPs to whitelist

Please could you also send me a link to the playbook once you're done? I'm not familiar with Ansible so I'd like to see how it works

**Comment by wu-lee** [comment]
The ansible playbooks, and some slightly ageing documentation, lives here:

https://github.com/DigitalCommons/technology-and-infrastructure

**Comment by wu-lee** [comment]
Ok, server is installed on dev-1

Managed to install but the playbook didn't seem to set up the user access properly. Had to do it manually for the time being. did it like this:

```
mysql> drop user 'boundary_service'@'%' ;
Query OK, 0 rows affected (0.02 sec)

mysql> create user 'boundary_service'@'%' identified by '<redacted>';
Query OK, 0 rows affected (0.03 sec)

mysql> grant all privileges on boundary_service.* to 'boundary_service'@'%' with grant option;
Query OK, 0 rows affected (0.02 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.01 sec)
```
This gets access working, will need to investigate why Ansible failed to get it working later. (The user existed, which is why I had to delete it, but the credentials weren't set)

Send @rogup the access credentials by DM.  They're also in the password-store repository (encrypted).

Firewall permits the two IPs Rohit named in a DM.

Although I don't have a login on those servers so I can't test it.  I have disabled the firewall and tested remote access using the above credentials works, however (from another server).  Mysql is configured to accept access for this user from any host. So if the firewall rules work as intended - they should - it should permit access from those IPs.

I've pushed the playbook - it's on the master branch of the technology-and-infrastructure project

https://github.com/DigitalCommons/technology-and-infrastructure/blob/master/ansible/sea-map-server.yml

One question to consider is - how big is the DB? 

Currently the server has 3.9G free out of 18G

So it it's bigger than 1 or 2 G then we should probably add disk space to the server.

I think John should be able to help with that, Colm has access to the Scaleway control panel for dev-1.

**Comment by rogup** [comment]
@wu-lee Thanks for this.

Don't think I'll have time to move over the database and test it before I leave.

For your question about size: we currently give our Cloudways MySql server 40GB storage (and it uses about 21GB). But I'm not sure how much is actually used for the data in the database, since some of this storage will be for the application and Ubuntu stuff.

**Comment by wu-lee** [comment]
The size of the mysql database can be estimated from the size of the directory `/var/lib/mysql` which contains all the DBs (including the system DB)

So on dev-1, which is an empty MySQL install:

```
root@dev-1:~# du -sh /var/lib/mysql
220M    /var/lib/mysql
```
We need to know the size of the boundary services server's mysql dir minus about 220M, mins some factor for any other DBs on there. Those can probably be estimated using the same trick on the appropriate subdirectory, of which I think there will be one per DB. I don't have a MySQL install handy to check that on though.

**Comment by King-Mob** [comment]
Plan is for @wu-lee to procure hetzner server, and run ansible script, creating `dev-2` which has MySQL on it, and then data can be moved from cloudways to hetzner

**Comment by lin-d-hop** [comment]
update: 
Database indexing required so roll out currently blocked by performance issues. 
Also need to implement server restart scripts
