### ISSUE TITLE
[Spike] Collecting user feedback in app

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#70]
## Description

We'd like to include a simple feedback form within LX, at least for the time between soft relaunch and main relaunch.

We're really just looking for the simplest feedback possible eg 'How is your LX experience today? 1-5 Anything else to tell us?'

- I'm hoping to understand:
-- Complexity of implementation (we want something simple!)
-- how we will access any feedback given
-- What flexibility we have in configuring the feedback form
-- An idea of the user experience once implemented. Eg will it pop up? (not ideal) or be accessed through an icon on the side? (better)

Let's time box this spike to 2 hrs max.

## Acceptance Criteria
- A small list of options for simple, out-of-the-box tools for user feedback collection.
- Links to docs that can help understand the q's in the description
- A recommendation for the preferred option(s) from a dev perspective.
- Estimated implementation time on preferred option(s)

**Comment by ColmDC** [comment]
This should be platform agnostic.

**Comment by rogup** [comment]
For the front-end

1.  https://feedbackfin.com/setup.html A pre-made React widget that we can plug straight in, and link it to a webhook. It doesn't seem to have a 1-5 star rating function, but allows written feedback which may be good enough. It popus up when a button is clicked.
2. Make our own simple UI for a feedback dialogue. This wouldn't take long, gives us more customisation, and might be easier to work with in the long term.

IMO option 2 is best.

For the backend:
1. Make our own backend API and store results in the backend MySql database. To view the feedback, we would need to do a manual query using the CLI on the backend. We do also want to make an admin panel for the database anyway (can't find the Git issue for this), which would make viewing and sorting/filtering the feedback easier.
2. Track feedback with Umami. https://umami.is/docs/track-events We already use Umami to track when the website is down, so we wouldn't need to do much more setup. It looks like the Track Events API is more designed for events like button clicks, rather than user feedback. So it's not clear whether it will suit this function, and be easy to analyse the results. Will need to play around with Umami a bit more to confirm. If we use this, we may be able to benefit from Umami's automations e.g. messages to Element, email summaries.

I think it would be worth investigating Umami a bit further and go with Option 2 if it feels suitable. Option 1 requires more work to set up the admin panel and also isn't as flexible, since it requires backend database migrations if we want to change the structure of the feedback.

**Comment by rogup** [comment]
@lin-d-hop if you're happy with my recommendations for the front-end, @ms0ur1s could maybe begin working on the UI since he's looking for work

**Comment by lin-d-hop** [comment]
@rogup I'd def agree to exploring Umami a little more. Would you continue the 2hrs extra. If we can fit this into Umami I think it is definitely the better options than a DB table :scream: 

Re the design task, let's look at this soon :)

**Comment by rogup** [comment]
@lin-d-hop I won't have time to fit this extra investigation in before I leave. But I think anyone will be able to pick this up.

I think the next steps in the investigation are to:
- Add some code to our front-end that sends some dummy feedback analytics using the Umami event API https://umami.is/docs/track-events 
- See how the events show up on Umami (hosted on Cloudron), and how easy it is to view/filter/sort feedback

**Comment by ms0ur1s** [comment]
@lin-d-hop, could you tell how to get access the Umami data on Cloudron, please?
