### ISSUE TITLE
Add polys and markers to own map

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/land-explorer-front-end#89]
## Description

Within markers and selectable polys (ie in commercial land reg data) we want a simple UI that enables the user to move this data to their own map.

This was discussed in a call on 01/08. Notes [here](https://docs.google.com/document/d/1V-0HH-JJAU6-RKqxDbvjTwrLnlSjHCzM0mhyVhnQvxs/edit).

## Acceptance Criteria
- A design both for polys (in land reg data) and for markers (eg in RGS data)
- Users should be able to add data to maps that have been shared with them and maps that they have saved already, as well as a new map
- If the user has than one map saved or shared with them they should be able to select which map this data should be saved to
- If the user currently is not on a saved map then they should have a helpful experience to select or save a map
- If the user has no maps saved or shared with them they should have a helpful experience to save a new map

**Comment by lin-d-hop** [comment]
Hi @MelissaMc20 
Have you made any progress on this? 
Don't stress if not and you've been wrapped up. Just looking forward to seeing :)

**Comment by MelissaMc20** [comment]
Hey @lin-d-hop - apologies, I sent John these > https://xd.adobe.com/view/a9b0649c-132d-482c-a89c-50582e032342-fce3/
before I went on holiday. @King-Mob should be able to give you more of an update :) 

I thought it best for him to focus on the functionality of it for now, in a phase 1 type thing and I'll look into moving the trays items around as a phase 2.

**Comment by lin-d-hop** [comment]
Thanks Mel, just had a look, these look great!

**Comment by King-Mob** [comment]
Also slightly unclear about the user flow if they click on an ownership polygon as they don't have a popup: the information appears in the sidebar

**Comment by rogup** [comment]
@King-Mob Before this is closed, we also need to fix the back-end updateMap function to not simply delete all markers and polys in the DB and resave them.

Since if a marker has been saved from a data group, it might not be in the marker data in the JSON, and it will be lost next time the map is saved.

The method needs to do something more clever, where only the changes are applied, which would also reduce DB operations and get us closer to the vision of multiple users being able to simultaneous collaborate on a map.

**Comment by rogup** [comment]
When I was thinking a bit about https://github.com/DigitalCommons/land-explorer-front-end/issues/137 , I think the easiest solution to this problem might be to immediately reload the map from the server after performing an 'add to map' operation. Then we know that the FE map data is up-to-date and contains the latest set of objects, so we won't lose data when saving.

This won't work if we want to concurrently edit maps (e.g. in two different browser tabs, or different users) but I suppose we don't need to support this yet.

**Comment by lin-d-hop** [comment]
It wont be long before we're supporting concurrent maps (two different users) so worth taking this into consideration. Another one for discussion tomorrow :)

**Comment by lin-d-hop** [comment]
@King-Mob is this in review because the task @rogup suggested above is complete?
I'm not sure how to test so can you close if you are happy? :pray:

**Comment by King-Mob** [comment]
@lin-d-hop 
1. It was in review because I forgot the suggestion existed.
2. I've now implemented the suggestion. You can test it by opening a map, turning on data layers and saving a data group item to the very map that you have open. The map will reload with the new item on it. Otherwise, no new behaviour. I can imagine autosave changing how this works.

**Comment by lin-d-hop** [comment]
Following on from bug spotted by @rogup in #176 we're going to resolve by implementing autosave after the single action of adding the dta group item to the map.

This comes after merging of #154 that simplifies saving.

**Comment by lin-d-hop** [comment]
I believe we are finally ready to close this one :tada:
